### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [jayda15/fh-work-apps#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jayda15** [comment]
Hey Matt,
 I've put the "mobile meta tag" or "viewport" from bootstrap into the header of the application.html.erb page. Is this correct?
Thanks!

**Comment by Matt-Lepley** [comment]
Awesome job! That is what I was looking for. :+1: 

Feel free to close this issue since you fixed it!

**Comment by jayda15** [comment]
Great, thank you!
